### PR TITLE
moved visible fields update to 1.0 upgrade

### PR DESCRIPTION
**Pull request by peterdd**

### CODE REVIEW

**Comment by Psychokiller1888** [comment]
Can't merge, it's conflicting

**Comment by peterdd** [comment]
ok, should i redo the changes and a new pull request or do you solve it?

**Comment by Psychokiller1888** [comment]
Well what's for sure I can't do it now, maybe this evening, but work is hell this period of time here

**Comment by peterdd** [comment]
ok, i will do a new pull request on current master, so no conflict.

**Pull request closed without merging**
