### PR TITLE
Restore dokuwiki formatting

### PR DESCRIPTION
**Pull request by jahto**

### CODE REVIEW

**Comment by Psychokiller1888** [comment]
That's normal at this state, right?

Welcome to your first Flyspray project! We hope that Flyspray provides you with many hours of increased productivity. If you have any issues, go to http://flyspray.org/support. You can customise this message by clicking the **Manage Project** link in the menu above...

Missing output plugin none!
Couldn't call none_TextFormatter::render()
Temporarly handled like it is HTML until fixed
Welcome to your first Flyspray project! We hope that Flyspray provides you with many hours of increased productivity. If you have any issues, go to http://flyspray.org/support. You can customise this message by clicking the **Manage Project** link in the menu above...

**Comment by jahto** [comment]
Trying to think fast when havink drunk a beer and two glasses of wine. Wait a few minutes...

**Comment by Psychokiller1888** [comment]
Dude, what about enjoying your drinks instead of working on FS???

**Comment by Psychokiller1888** [comment]
Actually it'swherever a formatted text is rendered => task desc, task comments, intro msgs etc

**Comment by jahto** [comment]
Yeah, I'll start enjoying the drinks now and look back here sometime later, not today anymore. Now it's good food, wine and beer.

**Pull request merged**
