### PR TITLE
Fix undefined offset

### PR DESCRIPTION
**Pull request by landrok**
PHP Notice:  Undefined offset: 2 in ../includes/class.flyspray.php on line 366
PHP Notice:  Undefined offset: 2 in ../includes/class.flyspray.php on line 367
When updating a task in quick editing mode

### CODE REVIEW

**Comment by landrok** [comment]
Flyspray 1.0 Alpha 2 
PHP 5.6.12 / Apache 2.4.10 Debian / MySql 5.5.44
error_reporting = E_ALL

**Comment by landrok** [comment]
[general]
cookiesalt="*"
output_buffering="on"
address_rewriting="0"
reminder_daemon="0"
passwdcrypt="md5"
doku_url="http://en.wikipedia.org/wiki/"
syntax_plugin="none"
update_check="1"

[database]
dbtype="mysqli"
dbhost="localhost"
dbname="flyspray"
dbuser="*"
dbpass="*"
dbprefix="flyspray_"

**Comment by peterdd** [comment]
Please do work on patches for github master always based on the github master.

**Comment by landrok** [comment]
Not reproduced after updating from github. Thanks

**Pull request closed without merging**
