### PR TITLE
A small redesign (just this page for now)

### PR DESCRIPTION
**Pull request by FrancescoGd**
As said in the mailing-list I did a small redesign of this page to make it a bit more coherent with the general theme (added link to download page, cleared some old tags and so on); find the message here: https://groups.google.com/d/msg/flyspray/UE51oxEvse4/QJA4Els-CgAJ
I may tackle other files in the setup process when I have some spare time, especially the other "step" pages, the missing italian translation (setup/lang) and sorting out setup/styles stuff.

### CODE REVIEW

**Comment by peterdd** [comment]
I probably discard the idea of trying to install the composer 3rd party dependencies with the webinstall of flyspray git development versions. It worked only on minor webhostings and in consequence mostly forwarded the user to go the ssh/shell way of doing the composer stuff.
So probably I drop composerit* files. I got distracted on polishing webinstall by caring of other bugs, sorry.

safe_mode is dropped by php5.4 ( php.net/manual/en/features.safe-mode.php )
Web hostings disable functions like shell_exec ( php.ini settings: disable_functions, allow_url_fopen, allow_url_include)

I will hopefully release Flyspray 1.0-rc8 this week, so people without ssh access on their web hosting can use install current release with included composer/3rd party stuff.

Meanwhile I do my development test installs with vagrant and put

* required php (and other) packets by linux distributions
* configure apache and configure mysql/postgresql
* fetching flyspray branches from github
* and also doing the composer stuff

into vagrant provision section, so after provision only need to insert db config and first user config into the webinstaller.

**Comment by FrancescoGd** [comment]
So do I leave this Composed related stuff as it is and don't care anymore? If so, I'll start to look at other parts...

**Comment by peterdd** [comment]
Yeah, will give you some hints when i am back at home. Whats your account on bugs.flyspray.org ?

**Comment by FrancescoGd** [comment]
francescogd

**Comment by FrancescoGd** [comment]
Sorry I borked a submission... feel free to close this PR and eventually remove any or both these files, I'll eventually resubmit the translation if you don't need composerit.php anymore.

**Comment by peterdd** [comment]
I dropped all stale assignees and assigned status of flyspray tasks on bugs.flyspray.org and your account there should now be able to selfassign a task you want (or open a new)

**Comment by FrancescoGd** [comment]
Thank you

**Pull request closed without merging**
