### PR TITLE
Replace direct access to input var by using a GPC method

### PR DESCRIPTION
**Pull request by landrok**
- Usage of GPC post method
- Remove unnecessary else + move OK comment for clarity purpose

### CODE REVIEW

**Comment by peterdd** [comment]
Hi landrok, could be a totally dumb question, but what is the benefit of using Post:val() instead of $_POST[]?
I know I wrote the captcha integration in a hurry to stop spambots, but whats so bad with passing $_POST[] here? Better 'testability'?

This is also a general question, sometimes that GPC layer in Flyspray looks so redundant to me.

**Comment by landrok** [comment]
Yes there is. A simple use case is when `$_POST` array key is not set. It would raise a notice. (For vicious bots).
Furthermore, I had a look at the check method, multidimensional arrays (ie. `$_POST['captcha_code']['my_second_dimension']`) are well skipped. (For very vicious bots)

Our GPC layer is a good abstract - could be improved. You're true, better testability is one of the good aspects to consider with this type of abstraction.

**Comment by peterdd** [comment]
What do you mean with 'are well skipped'? That the captcha can be bypassed?
I tried with an passing as post-array (captcha_code['blabla'], got only a warning, no bypass the check().

It spits a warning Warning: strtolower() expects parameter 1 to be string, array given in /***/dapphp/securimage/securimage.php on line 2358

Same with using Post::val() 
Will put a Post::inAlnum() before passing to $image->check()

**Comment by landrok** [comment]
Nice catch! There is a mistake in their "validate" method 
https://github.com/dapphp/securimage/blob/master/securimage.php#L2332
So, I will pull a little patch, less restrictive than inAlnum().

**Comment by peterdd** [comment]
I think we should stick to the default character set and keep it simple as possible:
https://www.phpcaptcha.org/documentation/customizing-securimage/#charset

which is a subset of [a-zA-Z0-9] as the documentation says.

**Comment by landrok** [comment]
So, https://github.com/Flyspray/flyspray/commit/af1b61f50e59132a8276036b1158a00646b731dd is great.

**Pull request merged**
