### PR TITLE
3 new translation strings

### PR DESCRIPTION
**Pull request by peterdd**

### CODE REVIEW

**Comment by Psychokiller1888** [comment]
Tag in German is "Tag" :) :) :)

**Comment by peterdd** [comment]
lol, with a complete different meaning ;-)

**Comment by Psychokiller1888** [comment]
Lol! So we should jsut rename them to Hashtag as everybody knows what they are

**Comment by peterdd** [comment]
Schildchen sounds cute in german I think. 

Hashtag in german spoken out with german pronounciation translates to "a day with smoking weed".. lol

**Comment by Psychokiller1888** [comment]
Looooool! I love you!

**Comment by jahto** [comment]
In finnish the translation would probably be 'tägi' or some of our own incomprehensible words. 'merkki' or 'jälki' comes first to my mind. but today, i'm on the mood of recommending that the final german translation should be globally accepted. must have something to do with what i'm eating. sauerkraut und bratwurst.

**Pull request merged**
