### PR TITLE
Add baseurl to global js scope

### PR DESCRIPTION
**Pull request by landrok**
See comment on FS#1737-IC

### CODE REVIEW

**Comment by peterdd** [comment]
Can you please merge that baseurl changes into one branch, so it can be reviewed as a whole before doing pull request to flyspray master?

**Comment by landrok** [comment]
Ok. Branch https://github.com/landrok/flyspray/tree/FS%231737-IC-baseurl
End of the rush. All tpl files which contained $baseurl have been rewrited.

**Comment by landrok** [comment]
Do you want me to close all these pulls and assemble them into new branch ?

**Comment by peterdd** [comment]
yes. for instance take patch-12 and merge the other patch-x to patch12.

**Comment by landrok** [comment]
Done

**Pull request closed without merging**
