### PR TITLE
fix FS#2330

### PR DESCRIPTION
**Pull request by peterdd**
and build the appropriate .csv filename also for the 'all projects' tasklist when doing csv export from a task search.

### CODE REVIEW

**Comment by landrok** [comment]
Some characters can break the filename. `"` or `\` for example.
Furthermore, multiple consecutive spaces or replacements are giving multiple consecutive underscores.
Maybe we should use `preg_replace` instead of  `str_replace` in order to have an explicit list of allowed characters (whitelisting).

```php
// digits and characters only
$outfile = sprintf(
  '%s_%s.csv',
  preg_replace('/[^\d*|^\w*]+/', '_', $proj->prefs['project_title']),
  date("Y-m-d")
);
```

**Comment by peterdd** [comment]
test_me

At least a project named _test"me_ works with " in csv export..

**Comment by peterdd** [comment]
test2

**Comment by peterdd** [comment]
Previous current Firefox, same testprojectname looks a bit different on IE (Edge) ...
test2_ie

**Comment by landrok** [comment]
Yes, in these cases, the renaming process is delegated to the browser.
If you look at the HTTP headers, for the `test"me` case, you will have something like 
`Content-Disposition :"attachment; filename=test"me_2017-01-24.csv"`

For the second case, as far as I can see, it's an encoding problem. I don't have any IE in my current location, I can't really help more.

**Comment by peterdd** [comment]
Well, not as easy as thought: http://stackoverflow.com/questions/93551/how-to-encode-the-filename-parameter-of-content-disposition-header-in-http

**Comment by peterdd** [comment]
I will open another task for that filename filtering on bugs.flyspray.org ...

**Comment by landrok** [comment]
For IE, can you try this:
```php
$outfile = sprintf(
  '%s_%s.csv',
  utf8_decode(preg_replace('/[^\d*|^\w*]+/', '_', $proj->prefs['project_title'])),
  date("Y-m-d")
);
```

**Comment by peterdd** [comment]
Any 'umlaut' stripped away before utf8_decode...

I think we need something like

```header('Content-Disposition: attachment; filename="'.$outfileascii.'"; filename*=utf-8\'\''.$outfileutf8);```

see RFC5987

**Comment by landrok** [comment]
The following seems good:
`header('Content-Disposition: attachment; filename=*=utf-8\'\''.$outfile);`

**Comment by peterdd** [comment]
played a bit, now IE-edge saves with uft8 chars, but firefox and chrome want save the ascii filename...

**Pull request merged**
