### PR TITLE
composer install hack

### PR DESCRIPTION
**Pull request by peterdd**
If some circumstances matched, required libraries can be installed by composer from browser interface without needing shell access to the server.

### CODE REVIEW

**Comment by peterdd** [comment]
Can someone please set execute permissions (chmod 755) on composerit.pl and composerit2.pl ?
I see no way how to do that over github.com website.

**Comment by Psychokiller1888** [comment]
Will try, can't from phone though...

**Comment by Psychokiller1888** [comment]
Should be ok: https://github.com/Flyspray/flyspray/commit/4e598dc79b80e4088168926ed977ff781ca0e29d

**Comment by peterdd** [comment]
Thx!

**Pull request merged**
