### PR TITLE
Uploaded image transparency

### PR DESCRIPTION
**Pull request by CaraesNaur**
Avatars that contain black have it made transparent, which is visually unappealing.  Switched transparency color to fuschia (#f0f).

### CODE REVIEW

**Comment by peterdd** [comment]
I found this on http://php.net/manual/en/function.imagecolortransparent.php#28035

> 
> I have found that ImageColorTransparent() works on true color images if and only if the transparent color is black.
> (PHP 4.2.3/GD 2.0)

Well, comment 14 years old and maybe this why black was choosen in Flyspray (guessing). What is the status in 2017?
Ideally the resizeImage() of Flyspray function detects the correct transparency values automatically for any type of uploaded gif and png.

**Comment by CaraesNaur** [comment]
I'm pretty sure that comment predates when PHP forked GD, so that issue may be fixed.

I agree that detecting an alpha channel first is a better solution, along with preserving any existing transparency instead of creating a new channel based on an (ultimately) arbitrary color.

I'll continue working on the better long term solution.

**Comment by peterdd** [comment]
Just if someone is interested in working on this: GD seems to be often a candit for bugs/fixes between php versions, for instance http://www.php.net/ChangeLog-7.php#7.0.11 https://bugs.php.net/bug.php?id=66005
So maybe figure out which works when for our current supported PHP-range php5.4-php7.1 (edge cases php5.3.*/php7.2.x+)

**Comment by peterdd** [comment]
inactivity of pull request. Do a new PR with a long term solution if problem still exists.

**Pull request closed without merging**
