### PR TITLE
Online notifications

### PR DESCRIPTION
**Pull request by jahto**
Backend work done. Didn't immediately break everything. Further testing needs a user interface. Peter, hurry up! It's you who voted for this feature to be in 1.0.

### CODE REVIEW

**Comment by jahto** [comment]
I suggest that we release anyway on 16. even if the user interface is not done, unless I really broke something. Hope not, I've been making modifications already and the notifications itself are already made.

**Comment by Psychokiller1888** [comment]
Peter is not reading notification email, so that's why he doesn't see :) :) :)

**Comment by jahto** [comment]
He's probably too busy trying to implement his favorite feature for 1.0 to notice that it has already been implemented. Or drinking too much because he believes it will not be in 1.0.

**Comment by peterdd** [comment]
No, today sleeping, meeting family, regeneration.

**Pull request merged**
